version: '3.8'

services:
  fivemserver:
    container_name: fivem-gta-server
    restart: on-failure
    stdin_open: true
    tty: true 
    build: .
    ports:
      - 30120:30120/tcp
      - 30120:30120/udp
    volumes:
      - ./server.cfg:/usr/share/voxtyproject/fivem-server/server.cfg